name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  build:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            server_ext: ""
            client_ext: ""
            label: linux-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            server_ext: ""
            client_ext: ""
            label: mac-arm
          - os: macos-latest
            goos: darwin
            goarch: amd64
            server_ext: ""
            client_ext: ""
            label: mac-intel
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            server_ext: .exe
            client_ext: .exe
            label: windows-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build server
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -tags server -o xmlui-mcp${{ matrix.server_ext }}

      - name: Build client
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -tags client -o xmlui-mcp-client${{ matrix.client_ext }}

      - name: Prepare package contents
        run: |
          mkdir -p package/xmlui-mcp

          # Copy binaries
          cp xmlui-mcp${{ matrix.server_ext }} package/xmlui-mcp/
          cp xmlui-mcp-client${{ matrix.client_ext }} package/xmlui-mcp/

          # Copy scripts
          cp run-mcp-client.bat package/xmlui-mcp/
          cp run-mcp-client.sh package/xmlui-mcp/
          cp prepare-binary.sh package/xmlui-mcp/
          chmod +x package/xmlui-mcp/run-mcp-client.sh
          chmod +x package/xmlui-mcp/prepare-binary.sh
          chmod +x package/xmlui-mcp/xmlui-mcp${{ matrix.server_ext }}
          chmod +x package/xmlui-mcp/xmlui-mcp-client${{ matrix.client_ext }}

          # Copy README
          cp README.md package/xmlui-mcp/

      - name: Create archive
        run: |
          cd package
          zip -r ../xmlui-mcp-${{ matrix.label }}.zip xmlui-mcp

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: xmlui-mcp-${{ matrix.label }}.zip
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
